### ISSUE TITLE
Need to reconcile b37 and hg19, per Geraldine's request

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/hellbender-protected#172]
Details are found in the discussion on  #167  ...

Basically, we take in hg19, but we act as if it was b37.  This is how Broad CGA operates, but we do not want to do that for tools that we will expose externally.  

@vdauwera Anything to add?

**Comment by LeeTL1220** [comment]
@vdauwera I bet the issue here is that we bring in the hg19 reference, but our target BED file uses the b37 convention.  And we drive all of our outputs from the target BED file.  Couldn't we just switch reference to b37 as SOP?  Broad sequencing uses b37, right?  And sequencing uses ``/seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta`` as well.  And despite the naming, isn't this b37?

So.... can't I just change the documentation to say ``b37`` wherever I said ``hg19``?

**Comment by vdauwera** [comment]
Broad production does indeed use b37 albeit under the name hg19 (which would be good to address separately as well). 

Enthusiastic yes on changing the docs and all filenames to b37 if this does not pose any technical problems for the tools (isn't there some dictionary validation?). Any files we distribute as resources will also need to be named appropriately.

**Comment by LeeTL1220** [comment]
TODO:

- [ ] Go into documentation (README.md) and replace ``hg19`` with ``b37``
- [ ] In the example, mention that the REF is actually b37
- [ ] In the plotter CLI, add a line that this only works with hg19 or b37 references.
